"""
workflow_engine.py — Person 3: The Runtime Executor (The Engine)
=================================================================
A pure Python workflow execution engine that reads Person 2's workflows.yaml
blueprint and executes it step-by-step by making HTTP requests against
Person 1's Prism Mock Server.

This engine does NOT call any LLM. It is entirely a programmatic workflow
player — handling variables, conditions, loops, and calling URLs in order.

Key features:
    - Loads and parses workflows.yaml (19 workflows, 133 endpoints)
    - Evaluates conditions with if/then/else and goto:step_id branching
    - Resolves endpoint templates ({SystemId}, {ChassisId}, etc.)
    - Makes HTTP requests (GET/POST/PATCH/DELETE) to the mock server
    - Extracts variables from JSON responses using JSONPath expressions
    - Handles loops (loop_over/loop_variable) with optional break_if
    - Chains output from one step into the next step's input
    - Renders output_template with all extracted variables
    - Evaluates next_workflows suggestions for cross-workflow chaining

Public API for Person 4 (MCP Wrapper):
    engine = WorkflowEngine('workflows.yaml', 'http://localhost:4000')
    engine.list_workflows()
    engine.get_workflow_detail('server_health_check')
    engine.run_workflow('server_health_check', {'SystemId': 'Server1'})

CLI usage:
    python workflow_engine.py list
    python workflow_engine.py detail server_health_check
    python workflow_engine.py run server_health_check -p SystemId=Server1
"""

import re
import json
import yaml
import logging
import requests
from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logger = logging.getLogger("workflow_engine")


# ===========================================================================
#  WorkflowEngine — the core class
# ===========================================================================
class WorkflowEngine:
    """
    The Runtime Executor — reads workflows.yaml and executes HTTP request
    chains with conditions, loops, and variable chaining.

    Parameters
    ----------
    workflows_file : str
        Path to the workflows.yaml file generated by Person 2.
    base_url : str
        Base URL of the API server (Person 1's Prism mock).
    timeout : int
        HTTP request timeout in seconds.
    """

    def __init__(
        self,
        workflows_file: str = "workflows.yaml",
        base_url: str = "http://localhost:4000",
        timeout: int = 30,
    ):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.workflows_file = workflows_file

        self._raw = self._load_workflows(workflows_file)
        self._meta: dict = self._raw.get("meta", {})
        self._workflow_map: Dict[str, dict] = {
            wf["name"]: wf for wf in self._raw.get("workflows", [])
        }

        logger.info(
            "Loaded %d workflows from %s", len(self._workflow_map), workflows_file
        )

    # -----------------------------------------------------------------------
    #  YAML loader
    # -----------------------------------------------------------------------
    @staticmethod
    def _load_workflows(path: str) -> dict:
        """Load and parse the workflows YAML file."""
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        if not data or "workflows" not in data:
            raise ValueError(f"Invalid workflows file: {path} (missing 'workflows' key)")
        return data

    # ===================================================================
    #  PUBLIC API  —  what Person 4 will call
    # ===================================================================

    def list_workflows(self) -> List[Dict[str, Any]]:
        """
        Return a summary list of every available workflow.

        Each item contains: name, description, category, parameters
        (with name/type/required/description/default), step_count,
        and raw_endpoint_count.
        """
        result: List[Dict[str, Any]] = []
        for wf in self._raw.get("workflows", []):
            result.append(
                {
                    "name": wf["name"],
                    "description": wf.get("description", ""),
                    "category": wf.get("category", ""),
                    "parameters": [
                        {
                            "name": p["name"],
                            "type": p.get("type", "string"),
                            "required": p.get("required", False),
                            "description": p.get("description", ""),
                            "default": p.get("default"),
                        }
                        for p in wf.get("parameters", [])
                    ],
                    "step_count": len(wf.get("steps", [])),
                    "raw_endpoint_count": len(wf.get("raw_endpoints", [])),
                }
            )
        return result

    def get_workflow_detail(self, name: str) -> Optional[Dict[str, Any]]:
        """
        Return the full detail of a single workflow (steps, params,
        raw_endpoints, output_template, next_workflows).

        Returns ``None`` if the name is not found.
        """
        wf = self._workflow_map.get(name)
        if wf is None:
            return None
        return {
            "name": wf["name"],
            "description": wf.get("description", ""),
            "category": wf.get("category", ""),
            "parameters": wf.get("parameters", []),
            "steps": wf.get("steps", []),
            "raw_endpoints": wf.get("raw_endpoints", []),
            "output_template": wf.get("output_template", ""),
            "next_workflows": wf.get("next_workflows", []),
        }

    def run_workflow(
        self, name: str, params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Execute a workflow by *name* with the given *params*.

        Returns a result dict::

            {
                "workflow_name": str,
                "success": bool,
                "steps_executed": [...],   # per-step result dicts
                "variables": {...},        # all extracted variables
                "output": str,             # rendered output_template
                "next_workflows": [...],   # applicable suggestions
                "error": str | None,
                "started_at": str,
                "finished_at": str,
            }
        """
        started = datetime.now(timezone.utc).isoformat()

        wf = self._workflow_map.get(name)
        if wf is None:
            return self._error_result(
                name,
                f"Workflow '{name}' not found. "
                f"Available: {sorted(self._workflow_map.keys())}",
                started,
            )

        # --- build initial context from defaults + caller params -----------
        context: Dict[str, Any] = {}
        for p in wf.get("parameters", []):
            if p.get("default") is not None:
                context[p["name"]] = p["default"]
        if params:
            context.update(params)

        steps = wf.get("steps", [])
        step_index = {s["step_id"]: idx for idx, s in enumerate(steps)}
        step_results: List[dict] = []
        current_idx = 0
        success = True
        error_msg: Optional[str] = None

        logger.info(
            "[Engine] ▶ Running workflow: %s (%d steps)", name, len(steps)
        )

        # --- step execution loop ------------------------------------------
        while current_idx < len(steps):
            step = steps[current_idx]
            step_id = step["step_id"]

            try:
                result = self._execute_step(
                    step, context, step_index, current_idx + 1, len(steps)
                )
                step_results.append(result)

                # Handle goto
                if result.get("action") == "goto":
                    target = result.get("goto_target", "")
                    if target in step_index:
                        current_idx = step_index[target]
                        continue
                    else:
                        logger.warning("goto target '%s' not found — continuing", target)

                # Handle stop
                if result.get("action") == "stop":
                    success = False
                    error_msg = f"Step '{step_id}' triggered stop: {result.get('error', '')}"
                    break

            except Exception as exc:
                logger.error("Step '%s' exception: %s", step_id, exc)
                step_results.append(
                    {"step_id": step_id, "status": "error", "error": str(exc)}
                )
                on_err = step.get("on_error", "continue")
                if on_err == "stop":
                    success = False
                    error_msg = f"Step '{step_id}' failed: {exc}"
                    break
                if on_err.startswith("goto:"):
                    target = on_err[5:]
                    if target in step_index:
                        current_idx = step_index[target]
                        continue

            current_idx += 1

        # --- render output & suggestions -----------------------------------
        output = self._render_output(wf.get("output_template", ""), context)
        suggested = self._evaluate_next_workflows(
            wf.get("next_workflows", []), context
        )
        finished = datetime.now(timezone.utc).isoformat()

        logger.info(
            "[Engine] ■ Finished %s — %s (%d steps executed)",
            name,
            "SUCCESS" if success else "FAILED",
            len(step_results),
        )

        return {
            "workflow_name": name,
            "success": success,
            "steps_executed": step_results,
            "variables": self._sanitize_variables(context),
            "output": output,
            "next_workflows": suggested,
            "error": error_msg,
            "started_at": started,
            "finished_at": finished,
        }

    # ===================================================================
    #  STEP EXECUTION
    # ===================================================================

    def _execute_step(
        self,
        step: dict,
        context: dict,
        step_index: dict,
        step_num: int,
        total: int,
    ) -> dict:
        """Dispatch a single step — evaluate condition, then single or loop."""
        step_id = step["step_id"]
        desc = step.get("description", "")
        logger.info("[Step %d/%d] %s — %s", step_num, total, step_id, desc)

        # --- 1. condition gate ---
        if "condition" in step:
            decision = self._evaluate_condition(step["condition"], context)
            if decision == "skip":
                logger.info("  ⊘ SKIPPED (condition not met)")
                return {"step_id": step_id, "status": "skipped", "action": "skip"}
            if decision.startswith("goto:"):
                target = decision[5:]
                logger.info("  ↪ GOTO %s", target)
                return {
                    "step_id": step_id,
                    "status": "skipped",
                    "action": "goto",
                    "goto_target": target,
                }
            # else "continue" — fall through

        # --- 2. loop or single execution ---
        if "loop_over" in step:
            return self._execute_loop(step, context, step_num, total)
        return self._execute_single(step, context)

    # -----------------------------------------------------------------------
    #  Single request execution
    # -----------------------------------------------------------------------
    def _execute_single(self, step: dict, context: dict) -> dict:
        """Execute one HTTP request and extract response variables."""
        step_id = step["step_id"]
        method = step.get("action", "GET").upper()
        endpoint = step.get("endpoint", "")

        # Resolve endpoint template
        resolved = self._resolve_template(endpoint, context)
        url = f"{self.base_url}{resolved}"

        # Resolve request body
        body = None
        if "request_body" in step:
            body = self._resolve_body(step["request_body"], context)

        logger.info("  → %s %s", method, resolved)
        resp_data, status, headers = self._http_request(method, url, body)
        logger.info("  ← %d", status)

        result: Dict[str, Any] = {
            "step_id": step_id,
            "status": "success" if 200 <= status < 400 else "error",
            "http_method": method,
            "endpoint": resolved,
            "status_code": status,
            "action": "continue",
        }

        # Handle HTTP errors
        if status >= 400:
            on_err = step.get("on_error", "continue")
            if on_err == "stop":
                result["action"] = "stop"
                result["error"] = f"HTTP {status}"
                return result
            if on_err.startswith("goto:"):
                result["action"] = "goto"
                result["goto_target"] = on_err[5:]
                return result
            # else continue

        # Extract variables
        if "extract" in step and resp_data:
            extracted = self._extract_values(resp_data, step["extract"], headers)
            context.update(extracted)
            result["extracted"] = {
                k: _preview(v) for k, v in extracted.items()
            }
            for k, v in extracted.items():
                logger.info("  ✓ %s = %s", k, _preview(v))

        return result

    # -----------------------------------------------------------------------
    #  Loop execution
    # -----------------------------------------------------------------------
    def _execute_loop(self, step: dict, context: dict, step_num: int, total: int) -> dict:
        """Execute a step in a loop over a collection variable."""
        step_id = step["step_id"]
        loop_source = step["loop_over"]
        loop_var = step["loop_variable"]
        break_cond = step.get("break_if")

        items = context.get(loop_source, [])
        if not isinstance(items, list):
            items = [items] if items else []

        logger.info("  ⟳ loop over %s (%d items)", loop_source, len(items))

        iterations: List[dict] = []
        for idx, item in enumerate(items):
            # Extract ID from URI path (last segment)
            if isinstance(item, str) and "/" in item:
                item_id = item.rstrip("/").split("/")[-1]
            else:
                item_id = str(item)

            context[loop_var] = item_id
            logger.info("  ⟳ [%d/%d] %s = %s", idx + 1, len(items), loop_var, item_id)

            try:
                iter_result = self._execute_single(step, context)
                iterations.append(iter_result)

                # Check for stop-on-error within loop
                if iter_result.get("action") == "stop":
                    return {
                        "step_id": step_id,
                        "status": "error",
                        "iterations_completed": len(iterations),
                        "iterations_total": len(items),
                        "action": "stop",
                        "error": iter_result.get("error", ""),
                    }

            except Exception as exc:
                on_err = step.get("on_error", "continue")
                if on_err == "stop":
                    return {
                        "step_id": step_id,
                        "status": "error",
                        "iterations_completed": len(iterations),
                        "iterations_total": len(items),
                        "action": "stop",
                        "error": str(exc),
                    }
                logger.warning("  ⟳ iteration error (continuing): %s", exc)
                continue

            # Check break_if
            if break_cond and self._evaluate_expression(break_cond, context):
                logger.info("  ⟳ break_if met: %s", break_cond)
                break

        return {
            "step_id": step_id,
            "status": "success",
            "iterations_completed": len(iterations),
            "iterations_total": len(items),
            "action": "continue",
        }

    # ===================================================================
    #  CONDITION EVALUATOR
    # ===================================================================

    def _evaluate_condition(self, cond: dict, ctx: dict) -> str:
        """
        Evaluate a condition block and return the action string:
        ``'continue'``, ``'skip'``, or ``'goto:<step_id>'``.
        """
        expr = cond.get("if", "")
        then_act = cond.get("then", "continue")
        else_act = cond.get("else", "skip")
        return then_act if self._evaluate_expression(expr, ctx) else else_act

    def _evaluate_expression(self, expr: str, ctx: dict) -> bool:
        """
        Safely evaluate a boolean expression.

        Supports:
            - ``var == 'value'``  /  ``var != 'value'``
            - ``var == true``  /  ``var == false``  /  ``var == null``
            - ``expr1 and expr2``
            - ``expr1 or expr2``
        """
        expr = expr.strip()
        if not expr:
            return False

        # Handle OR (lower precedence)
        parts = self._safe_split(expr, " or ")
        if len(parts) > 1:
            return any(self._evaluate_expression(p, ctx) for p in parts)

        # Handle AND
        parts = self._safe_split(expr, " and ")
        if len(parts) > 1:
            return all(self._evaluate_expression(p, ctx) for p in parts)

        # Atomic comparison
        return self._eval_atomic(expr, ctx)

    def _eval_atomic(self, expr: str, ctx: dict) -> bool:
        """Evaluate a single comparison (``a == b`` or ``a != b``)."""
        for op in ("!=", "=="):
            if op in expr:
                left_raw, right_raw = expr.split(op, 1)
                left = self._resolve_value(left_raw.strip(), ctx)
                right = self._resolve_value(right_raw.strip(), ctx)
                return (left != right) if op == "!=" else (left == right)
        # No operator → truthy check
        return bool(self._resolve_value(expr, ctx))

    @staticmethod
    def _safe_split(expr: str, delim: str) -> List[str]:
        """Split *expr* by *delim* while respecting quoted strings."""
        parts: List[str] = []
        buf = ""
        in_q = False
        qc = ""
        i = 0
        while i < len(expr):
            ch = expr[i]
            if not in_q and ch in ("'", '"'):
                in_q, qc = True, ch
                buf += ch
            elif in_q and ch == qc:
                in_q = False
                buf += ch
            elif not in_q and expr[i:].startswith(delim):
                parts.append(buf.strip())
                buf = ""
                i += len(delim)
                continue
            else:
                buf += ch
            i += 1
        if buf.strip():
            parts.append(buf.strip())
        return parts

    @staticmethod
    def _resolve_value(token: str, ctx: dict) -> Any:
        """Resolve a token to a Python value (literal, keyword, or variable)."""
        token = token.strip()
        # Quoted string
        if len(token) >= 2 and token[0] in ("'", '"') and token[-1] == token[0]:
            return token[1:-1]
        # Keywords
        if token == "true":
            return True
        if token == "false":
            return False
        if token in ("null", "None"):
            return None
        # Numeric
        try:
            return int(token)
        except ValueError:
            pass
        try:
            return float(token)
        except ValueError:
            pass
        # Variable look-up
        return ctx.get(token)

    # ===================================================================
    #  TEMPLATE RESOLUTION
    # ===================================================================

    @staticmethod
    def _resolve_template(template: str, ctx: dict) -> str:
        """Replace ``{var}`` placeholders with values from *ctx*."""

        def _repl(m):
            val = ctx.get(m.group(1))
            return str(val) if val is not None else m.group(0)

        return re.sub(r"\{(\w+)\}", _repl, template)

    def _resolve_body(self, body: Any, ctx: dict) -> Any:
        """Recursively resolve templates inside a request body structure."""
        if isinstance(body, str):
            # If the entire string is '{var}', return the raw value (may be
            # list / dict / bool) instead of a string.
            clean = body.strip().strip("'\"")
            m = re.match(r"^\{(\w+)\}$", clean)
            if m:
                raw = ctx.get(m.group(1))
                return raw if raw is not None else body
            return self._resolve_template(body, ctx)
        if isinstance(body, dict):
            return {k: self._resolve_body(v, ctx) for k, v in body.items()}
        if isinstance(body, list):
            return [self._resolve_body(v, ctx) for v in body]
        return body

    # ===================================================================
    #  HTTP REQUEST
    # ===================================================================

    def _http_request(
        self, method: str, url: str, body: Any = None
    ) -> Tuple[dict, int, dict]:
        """
        Issue an HTTP request. Returns ``(json_body, status_code, headers)``.

        Connection/timeout errors return a synthetic 503/504 with empty body.
        """
        hdrs = {"Content-Type": "application/json", "Accept": "application/json"}

        dispatch = {
            "GET": lambda: requests.get(url, headers=hdrs, timeout=self.timeout),
            "POST": lambda: requests.post(url, headers=hdrs, json=body, timeout=self.timeout),
            "PATCH": lambda: requests.patch(url, headers=hdrs, json=body, timeout=self.timeout),
            "DELETE": lambda: requests.delete(url, headers=hdrs, timeout=self.timeout),
            "PUT": lambda: requests.put(url, headers=hdrs, json=body, timeout=self.timeout),
        }

        try:
            resp = dispatch.get(method, dispatch["GET"])()
            try:
                data = resp.json()
            except (json.JSONDecodeError, ValueError):
                data = {}
            return data, resp.status_code, dict(resp.headers)

        except requests.exceptions.ConnectionError:
            logger.error("Connection refused: %s", url)
            return {}, 503, {}
        except requests.exceptions.Timeout:
            logger.error("Timeout: %s", url)
            return {}, 504, {}
        except Exception as exc:  # noqa: BLE001
            logger.error("Request error: %s", exc)
            return {}, 500, {}

    # ===================================================================
    #  JSONPATH EXTRACTOR  (custom, zero extra dependencies)
    # ===================================================================

    def _extract_values(
        self, data: dict, extract_map: dict, headers: Optional[dict] = None
    ) -> dict:
        """Extract multiple variables from a JSON response."""
        out: Dict[str, Any] = {}
        for var_name, path_expr in extract_map.items():
            try:
                out[var_name] = self._jsonpath(data, path_expr, headers)
            except Exception as exc:  # noqa: BLE001
                logger.warning("extract '%s' via '%s' failed: %s", var_name, path_expr, exc)
                out[var_name] = None
        return out

    def _jsonpath(
        self, data: Any, expr: str, headers: Optional[dict] = None
    ) -> Any:
        """
        Evaluate a JSONPath-like expression against *data*.

        Handles Redfish-specific patterns:
            ``$.Status.Health``
            ``$.Members[*].@odata.id``
            ``$.PowerControl[0].PowerConsumedWatts``
            ``$.Members@odata.count``
            ``$.Actions.['#CertificateService.GenerateCSR'].target``
            ``$.headers.X-Auth-Token``  (response-header extraction)
        """
        if not expr or not expr.startswith("$"):
            return None

        # Special: response-header extraction
        if expr.startswith("$.headers."):
            key = expr[len("$.headers."):]
            return (headers or {}).get(key)

        path = expr[2:] if expr.startswith("$.") else expr[1:]
        tokens = self._tokenize_path(path)
        return self._walk(data, tokens)

    # ---- path tokenizer ---------------------------------------------------

    @staticmethod
    def _tokenize_path(path: str) -> list:
        """
        Tokenize a JSONPath-like path into a list of segments.

        Handles dots, brackets, ``@odata.*`` keys, and array indices.

        Examples::

            'Status.Health'                     → ['Status', 'Health']
            'Members[*].@odata.id'              → ['Members', '*', '@odata.id']
            'PowerControl[0].PowerConsumedWatts' → ['PowerControl', 0, 'PowerConsumedWatts']
            'Members@odata.count'               → ['Members@odata.count']
            "Actions.['#Cert...'].target"       → ['Actions', '#Cert...', 'target']
            'Fans[*].Status.Health'             → ['Fans', '*', 'Status', 'Health']
            'Devices[*].Name'                   → ['Devices', '*', 'Name']
        """
        tokens: list = []
        buf = ""
        i = 0
        while i < len(path):
            ch = path[i]

            # --- bracket notation ---
            if ch == "[":
                if buf:
                    tokens.append(buf)
                    buf = ""
                j = path.index("]", i)
                inner = path[i + 1 : j]
                if inner == "*":
                    tokens.append("*")
                elif inner.startswith("'") and inner.endswith("'"):
                    tokens.append(inner[1:-1])
                elif inner.startswith('"') and inner.endswith('"'):
                    tokens.append(inner[1:-1])
                else:
                    try:
                        tokens.append(int(inner))
                    except ValueError:
                        tokens.append(inner)
                i = j + 1
                # skip a following dot separator
                if i < len(path) and path[i] == ".":
                    i += 1
                continue

            # --- dot handling ---
            if ch == ".":
                # @odata.xxx  →  keep as part of current token
                if buf.endswith("@odata"):
                    buf += ch
                else:
                    if buf:
                        tokens.append(buf)
                        buf = ""
            else:
                buf += ch
            i += 1

        if buf:
            tokens.append(buf)
        return tokens

    # ---- recursive walker -------------------------------------------------

    def _walk(self, data: Any, tokens: list) -> Any:
        """Walk *tokens* through *data*, returning the matched value."""
        if not tokens:
            return data
        if data is None:
            return None

        head, rest = tokens[0], tokens[1:]

        # Wildcard — fan-out across list elements
        if head == "*":
            if isinstance(data, list):
                return [self._walk(item, rest) for item in data] if rest else data
            return None

        # Integer index
        if isinstance(head, int):
            if isinstance(data, list) and head < len(data):
                return self._walk(data[head], rest)
            return None

        # Dict key look-up
        if isinstance(data, dict):
            if head in data:
                return self._walk(data[head], rest)
            return None

        # If data is a list but token is a string key, map over elements
        if isinstance(data, list):
            return [
                self._walk(item, tokens)
                for item in data
                if isinstance(item, dict)
            ]

        return None

    # ===================================================================
    #  OUTPUT RENDERING
    # ===================================================================

    def _render_output(self, template: str, ctx: dict) -> str:
        """Render the workflow's ``output_template`` with extracted variables."""
        if not template:
            return ""
        return self._resolve_template(template, ctx)

    def _evaluate_next_workflows(
        self, next_wfs: list, ctx: dict
    ) -> List[Dict[str, str]]:
        """Return the subset of ``next_workflows`` whose conditions hold."""
        out: List[Dict[str, str]] = []
        for nw in next_wfs:
            cond = nw.get("if", "")
            if not cond or self._evaluate_expression(cond, ctx):
                out.append(
                    {"workflow": nw["workflow"], "reason": nw.get("reason", "")}
                )
        return out

    # ===================================================================
    #  HELPERS
    # ===================================================================

    @staticmethod
    def _sanitize_variables(ctx: dict) -> dict:
        """Return a JSON-safe copy of the context for the result payload."""
        clean: dict = {}
        for k, v in ctx.items():
            try:
                json.dumps(v)
                clean[k] = v
            except (TypeError, ValueError):
                clean[k] = str(v)
        return clean

    @staticmethod
    def _error_result(name: str, msg: str, started: str) -> dict:
        return {
            "workflow_name": name,
            "success": False,
            "steps_executed": [],
            "variables": {},
            "output": "",
            "next_workflows": [],
            "error": msg,
            "started_at": started,
            "finished_at": datetime.now(timezone.utc).isoformat(),
        }


# ===========================================================================
#  Utility
# ===========================================================================

def _preview(value: Any, max_len: int = 100) -> str:
    """Produce a short string preview of a value for logging."""
    s = str(value)
    return s[:max_len] + "…" if len(s) > max_len else s


# ===========================================================================
#  CLI
# ===========================================================================

def main() -> None:
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        prog="workflow_engine",
        description="Person 3 — Workflow Runtime Engine",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  %(prog)s list
  %(prog)s detail server_health_check
  %(prog)s run discover_service_root
  %(prog)s run server_health_check -p SystemId=Server1
  %(prog)s run firmware_update -p ImageURI=http://fw.img -p TargetVersion=2.0
  %(prog)s list --json
        """,
    )

    parser.add_argument(
        "command",
        choices=["list", "detail", "run"],
        help="list = show all workflows · detail = inspect one · run = execute one",
    )
    parser.add_argument("workflow", nargs="?", help="Workflow name (detail/run)")
    parser.add_argument(
        "-f", "--file", default="workflows.yaml", help="Workflows YAML file"
    )
    parser.add_argument(
        "-u", "--url", default="http://localhost:4000", help="API base URL"
    )
    parser.add_argument(
        "-p", "--param", action="append", default=[], help="key=value (repeatable)"
    )
    parser.add_argument(
        "-t", "--timeout", type=int, default=30, help="HTTP timeout (s)"
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Debug logging")
    parser.add_argument("--json", action="store_true", help="Output as JSON")

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(message)s",
    )

    try:
        engine = WorkflowEngine(args.file, args.url, args.timeout)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    # -------------------------------------------------------------------
    #  LIST
    # -------------------------------------------------------------------
    if args.command == "list":
        wfs = engine.list_workflows()
        if args.json:
            print(json.dumps(wfs, indent=2))
            return

        print(f"\n{'═' * 72}")
        print(f"  AVAILABLE WORKFLOWS  ({len(wfs)})")
        print(f"{'═' * 72}\n")

        by_cat: Dict[str, list] = {}
        for w in wfs:
            by_cat.setdefault(w["category"] or "other", []).append(w)

        for cat in sorted(by_cat):
            print(f"  ┌─ {cat.upper()}")
            for w in by_cat[cat]:
                params_str = ", ".join(
                    f"{'*' if p['required'] else ''}{p['name']}"
                    for p in w["parameters"]
                )
                print(
                    f"  │  {w['name']:42s}  {w['step_count']:2d} steps  "
                    f"{w['raw_endpoint_count']:3d} endpoints"
                )
                desc = w["description"]
                if len(desc) > 78:
                    desc = desc[:75] + "..."
                print(f"  │    {desc}")
                if params_str:
                    print(f"  │    params: {params_str}")
            print(f"  └{'─' * 70}\n")

    # -------------------------------------------------------------------
    #  DETAIL
    # -------------------------------------------------------------------
    elif args.command == "detail":
        if not args.workflow:
            print("ERROR: workflow name required", file=sys.stderr)
            sys.exit(1)

        detail = engine.get_workflow_detail(args.workflow)
        if detail is None:
            print(f"ERROR: '{args.workflow}' not found", file=sys.stderr)
            sys.exit(1)

        if args.json:
            print(json.dumps(detail, indent=2, default=str))
            return

        print(f"\n{'═' * 72}")
        print(f"  WORKFLOW: {detail['name']}")
        print(f"{'═' * 72}")
        print(f"  Category    : {detail['category']}")
        print(f"  Description : {detail['description']}")

        if detail["parameters"]:
            print(f"\n  PARAMETERS:")
            for p in detail["parameters"]:
                req = "(required)" if p.get("required") else "(optional)"
                dfl = f" [default: {p.get('default')}]" if p.get("default") else ""
                print(f"    {p['name']:20s} {req:12s} {p.get('description', '')}{dfl}")

        print(f"\n  STEPS ({len(detail['steps'])}):")
        for i, s in enumerate(detail["steps"], 1):
            flags = []
            if "condition" in s:
                flags.append("cond")
            if "loop_over" in s:
                flags.append(f"loop:{s['loop_over']}")
            if "break_if" in s:
                flags.append("break_if")
            if "on_error" in s:
                flags.append(f"err:{s['on_error']}")
            tag = f"  [{', '.join(flags)}]" if flags else ""
            print(
                f"    {i:2d}. [{s['step_id']}] "
                f"{s.get('action', 'GET')} {s.get('endpoint', '')}{tag}"
            )
            print(f"        {s.get('description', '')}")

        if detail["raw_endpoints"]:
            print(f"\n  RAW ENDPOINTS ({len(detail['raw_endpoints'])}):")
            for ep in detail["raw_endpoints"]:
                print(f"    • {ep}")

        if detail.get("next_workflows"):
            print(f"\n  SUGGESTED NEXT:")
            for nw in detail["next_workflows"]:
                print(f"    → {nw.get('workflow', '')}  (if {nw.get('if', 'always')})")
                print(f"      {nw.get('reason', '')}")

        if detail.get("output_template"):
            print(f"\n  OUTPUT TEMPLATE:")
            for line in detail["output_template"].split("\n"):
                print(f"    {line}")

        print()

    # -------------------------------------------------------------------
    #  RUN
    # -------------------------------------------------------------------
    elif args.command == "run":
        if not args.workflow:
            print("ERROR: workflow name required", file=sys.stderr)
            sys.exit(1)

        params: Dict[str, str] = {}
        for kv in args.param:
            if "=" in kv:
                k, v = kv.split("=", 1)
                params[k] = v
            else:
                print(f"WARNING: ignoring '{kv}' (use key=value)", file=sys.stderr)

        print(f"\n{'═' * 72}")
        print(f"  ▶ EXECUTING: {args.workflow}")
        print(f"  Server : {args.url}")
        if params:
            print(f"  Params : {params}")
        print(f"{'═' * 72}\n")

        result = engine.run_workflow(args.workflow, params)

        if args.json:
            safe = {
                "workflow_name": result["workflow_name"],
                "success": result["success"],
                "steps_executed": result["steps_executed"],
                "output": result["output"],
                "next_workflows": result["next_workflows"],
                "error": result["error"],
                "started_at": result["started_at"],
                "finished_at": result["finished_at"],
            }
            print(json.dumps(safe, indent=2, default=str))
            return

        print(f"\n{'═' * 72}")
        print(f"  ■ RESULT")
        print(f"{'═' * 72}")
        print(f"  Workflow : {result['workflow_name']}")
        print(f"  Success  : {'✓' if result['success'] else '✗'}")
        print(f"  Steps    : {len(result['steps_executed'])} executed")
        print(f"  Time     : {result['started_at']} → {result['finished_at']}")

        if result["error"]:
            print(f"  Error    : {result['error']}")

        # Step summary
        print(f"\n  STEP LOG:")
        for sr in result["steps_executed"]:
            icon = {"success": "✓", "skipped": "⊘", "error": "✗"}.get(
                sr.get("status", ""), "?"
            )
            extra = ""
            if "status_code" in sr:
                extra = f" [{sr['status_code']}]"
            if "iterations_completed" in sr:
                extra += f" ({sr['iterations_completed']}/{sr['iterations_total']} iters)"
            if sr.get("goto_target"):
                extra += f" → goto:{sr['goto_target']}"
            print(f"    {icon} {sr['step_id']}{extra}")

        if result["output"]:
            print(f"\n  OUTPUT:")
            for line in result["output"].split("\n"):
                print(f"  {line}")

        if result["next_workflows"]:
            print(f"\n  SUGGESTED NEXT:")
            for nw in result["next_workflows"]:
                print(f"    → {nw['workflow']}: {nw['reason']}")

        print(f"\n{'═' * 72}\n")


if __name__ == "__main__":
    main()
